# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

EAPI=5

inherit perl-module

S=${WORKDIR}/Net-Growl-0.99

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Net-Growl&mode=dist"
SRC_URI="mirror://cpan/authors/id/N/NM/NMCFARL/Net-Growl-0.99.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="alpha amd64 arm hppa ia64 m68k mips ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd"

DEPEND="
	dev-lang/perl
	dev-perl/Module-Build
"
